version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: pg_sftp
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'bestuser'
      POSTGRES_PASSWORD: 'bestuser'
      POSTGRES_DB: 'my_db'
    ports:
      - '5432:5432'

    volumes:
      - ./pgfiles:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
