### GET /customers/1 - Отримати інформацію про користувача за ідентифікатором 1
GET http://localhost:9000/api/customers/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdCIsImlhdCI6MTcxNzY4NzkzMSwiZXhwIjoxNzE3Njg5NzMxfQ.3mRYGFWSC-bhROV3euwuv9GXS1Llv0B-QOde9zcRylW_CCe_5wD4aNKGISAj-SA7ebA4ujz6pRr6SrXkZnFoog


### check auth token generation
POST http://localhost:9000/api/auth
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
> {%
    client.global.set("auth_token", response.body.token);
%}
### GET /customers - Отримати інформацію про всіх користувачів
GET http://localhost:9000/api/customers
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdCIsImlhdCI6MTcxNzY4NzkzMSwiZXhwIjoxNzE3Njg5NzMxfQ.3mRYGFWSC-bhROV3euwuv9GXS1Llv0B-QOde9zcRylW_CCe_5wD4aNKGISAj-SA7ebA4ujz6pRr6SrXkZnFoog
### POST /customers - Створити нового користувача
POST http://localhost:9000/api/customers
Content-Type: application/json

{
    "name": "Rogue Earls",
    "email": "john@example.com",
    "age": 22,
    "accounts": [],
    "password": "qwerty",
    "phone": "3213-123123"
}
### POST /customers - Створити нового користувача2
POST http://localhost:9000/api/customers
Content-Type: application/json

{
    "name": "Demond Burditt",
    "email": "tzivia_tresslerws@voted.ke",
    "age": 12,
    "accounts": []
}

### PUT /customers/1 - Змінити дані користувача за ідентифікатором 1
PUT http://localhost:9000/api/customers/1
Content-Type: application/json

{
    "id": 1,
    "name": "Karna Hennis",
    "email": "johndoe@example.com",
    "age": 15,
    "accounts": []
}

### DELETE /customers/1 - Видалити користувача за ідентифікатором 1
DELETE http://localhost:9000/api/customers/1


###POST /customers/1/accounts - Створити рахунок для користувача за ідентифікатором 1
POST http://localhost:9000/api/customers/1/accounts
Content-Type: application/json

{
    "currency": "USD",
    "balance": 110.00
}

### DELETE /customers/1/accounts/1 - Видалити рахунок з ідентифікатором 1 для користувача за ідентифікатором 1
DELETE http://localhost:9000/api/customers/1/accounts/1
